version: '3.8'

services:
  backend-api:
    build:
      context: ./backend-api
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=mongodb://story-storage:27017/stories
      - AWS_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - S3_BUCKET=media
      - S3_ENDPOINT=http://localstack:4566
      - S3_PUBLIC_URL=http://localhost:4566
    depends_on:
      - story-storage
      - localstack
    entrypoint: ["./wait-for-it.sh", "story-storage:27017", "--", "./app"]

  story-storage:
    image: mongo:latest
    container_name: story-storage
    ports:
      - "27017:27017"
    volumes:
      - story-data:/data/db

  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME:-localstack-main}"
    image: localstack/localstack:s3-latest
    ports:
      - "127.0.0.1:4566:4566"            # LocalStack Gateway
    environment:
      - DEBUG=${DEBUG:-0}
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"

volumes:
  story-data: